[package]
name = "geosia_client"
version = "0.0.0"
description = "Geosia game client"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
# Local
gs_schemas.workspace = true
# Remote
bevy.workspace = true
